---
- name: Install nginx
  hosts: [PROD_WEB]
  become: true

  tasks:
  - name: Install Nginx
    yum:
      name: nginx
      state: present
  - name: replacement nginx.conf
    template:
      src=nginx.conf.j2
      dest=/etc/nginx/nginx.conf
  - name: Start Nginx
    service:
      name: nginx
      state: started
  - name: Enable service nginx
    systemd:
      name: nginx
      enabled: yes
  - name: Added config for virtualhost
    template:
      src={{ item }}
      dest=/etc/nginx/conf.d/{{ item|replace(".j2", "")  }}
    loop:
      - first_vhost.conf.j2
      - second_vhost.conf.j2
    notify:
    - Reload Nginx
  handlers:
  - name: Reload Nginx
    service: name=nginx state=reloaded
